version: '3.8'
services:
    #PHP Service
    app: &app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www:delegated
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    worker:
        <<: *app
        command:
            - "php"
            - "artisan"
            - "horizon"

    #Nginx Service
    webserver:
        image: nginx:1.22-alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www:delegated
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
